sudo: false
cache: bundler

script: "bundle exec rake spec"

rvm:
  - 1.9.3
  - 2.1.5
  - 2.2.0

bundler_args: "--binstubs --without development"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
